### ISSUE TITLE
Form does not submit

### ISSUE THREAD

**Issue by BartBucknill** [FAC-11/week1-dyrt#77]
One option for making the form submittable is [formspree](https://formspree.io/). You simply embed an HTML snippet and your some email details.

**Comment by lucymonie** [comment]
Also, if you don't get to fix this before presentations, it would be a good idea to add a section in the readme noting that the form submit isn't working and note what work you think needs doing in order to make it work. It's good to document anything like this as it makes it easier if you come back to resume work on it later. I'm sure @jsms90 will say these should be in issues :smiley:
